-- Generated by spritter v1.2.3 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 2, 3 },
  ["file_count"] = 1,
  ["height"] = 128,
  ["line_length"] = 1,
  ["lines_per_file"] = 1,
  ["scale"] = 0.5,
  ["shift"] = {x = 0 / 64, y = 0 / 64},
  ["sprite_count"] = 1,
  ["width"] = 128,
}
